2022-02-14 03:13:58,315 INFO    MainThread:3243 [internal.py:wandb_internal():92] W&B internal server running at pid: 3243, started at: 2022-02-14 03:13:58.314917
2022-02-14 03:13:58,323 DEBUG   HandlerThread:3243 [handler.py:handle_request():131] handle_request: run_start
2022-02-14 03:13:58,324 INFO    WriterThread:3243 [datastore.py:open_for_write():77] open: /home/pi/FedML-Server/executor/wandb/offline-run-20220214_031356-1ihgcp8c/run-1ihgcp8c.wandb
2022-02-14 03:13:58,330 DEBUG   HandlerThread:3243 [meta.py:__init__():36] meta init
2022-02-14 03:13:58,330 DEBUG   HandlerThread:3243 [meta.py:__init__():50] meta init done
2022-02-14 03:13:58,330 DEBUG   HandlerThread:3243 [meta.py:probe():210] probe
2022-02-14 03:13:58,333 DEBUG   HandlerThread:3243 [meta.py:_setup_git():200] setup git
2022-02-14 03:13:58,363 DEBUG   HandlerThread:3243 [meta.py:_setup_git():207] setup git done
2022-02-14 03:13:58,363 DEBUG   HandlerThread:3243 [meta.py:_save_pip():54] save pip
2022-02-14 03:13:58,364 DEBUG   HandlerThread:3243 [meta.py:_save_pip():68] save pip done
2022-02-14 03:13:58,364 DEBUG   HandlerThread:3243 [meta.py:probe():248] probe done
2022-02-14 03:14:00,930 WARNING MainThread:3243 [internal.py:wandb_internal():152] Internal process interrupt: 1
2022-02-14 03:14:07,939 WARNING MainThread:3243 [internal.py:is_dead():381] Internal process exiting, parent pid 3225 disappeared
2022-02-14 03:14:07,939 ERROR   MainThread:3243 [internal.py:wandb_internal():148] Internal process shutdown.
2022-02-14 03:14:08,328 INFO    SenderThread:3243 [sender.py:finish():1075] shutting down sender
2022-02-14 03:14:08,527 INFO    WriterThread:3243 [datastore.py:close():281] close: /home/pi/FedML-Server/executor/wandb/offline-run-20220214_031356-1ihgcp8c/run-1ihgcp8c.wandb
2022-02-14 03:14:08,535 INFO    HandlerThread:3243 [handler.py:finish():739] shutting down handler
2022-02-14 03:14:08,537 INFO    MainThread:3243 [internal.py:handle_exit():79] Internal process exited
